### ISSUE TITLE
"Impossible class count value 0"

### ISSUE THREAD

**Issue by theredled** [Nono1971/doctrine-yuml-bundle#10]
I can't generate any file:
```
$ app/console yuml:mappings
20:35:38 ERROR     [console] Error thrown while running command "yuml:mappings". Message: "Impossible class count value 0" ["exception" => Exception { …},"command" => "yuml:mappings","message" => "Impossible class count value 0"]

In StringGeneratorHelper.php line 104:
                                  
  Impossible class count value 0  
                                  

yuml:mappings [-f|--filename FILENAME] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

Using SF 3.4.

Some stacktrace bits:

> StringGeneratorHelper->getCountSide(0)
> in vendor/onurb/doctrine-metadata-grapher/lib/Onurb/Doctrine/ORMMetadataGrapher/YumlMetadataGrapher/StringGenerator/StringGeneratorHelper.php (line 67)
> StringGeneratorHelper->makeDoubleSidedLinkString('[QsContractorBundle.Entity.ContractorAttachment|isVisible : integer;expirationDate : date]', '[QsContractorBundle.Entity.Signature|firstname : string (255);lastname : string (255);email : string (255);agree : boolean;creationDate : datetime;+id : integer]', false, false, 'Attachments', 0, 'Signature', 1)
> in vendor/onurb/doctrine-metadata-grapher/lib/Onurb/Doctrine/ORMMetadataGrapher/YumlMetadataGrapher/StringGenerator.php (line 172)

**Comment by Nono1971** [comment]
Hi ! 
This is not an issue, this  error message is throwed when a bidirectional relation between two entities is not correctly reversed.
You can debug it with the profiler who indicates which relation is involved. In your case, the relation involved is between ContractorAttachment and Signature entities...

OK, I'll think about making a more explicit message ;)

**Comment by theredled** [comment]
Ok, fine after correcting all schemas errors AND orphan inversed-by attribute (not raised as errors by doctrine).

But definitely the error message could be more explicit!
Thanks
