### ISSUE TITLE
Bundle uploads visualization of entities without any notice to yuml.me

### ISSUE THREAD

**Issue by ireznik** [Nono1971/doctrine-yuml-bundle#11]
This bundle uploads the visualization of your entities within the project to yuml.me and provides a public url. I did not find any possibility to delete the image from public access. This should be prominent in the documentation and should be optional. Rather than upload this (critical) information I would prefer to be asked before the data is processed

**Comment by Nono1971** [comment]
Hi !
Infact, it is explicit in the description of the bundle that it uses yuml.me as a third party api, I'm not responsible of yuml.me privacy politic ! can't blame me for that ^^

I don't know if there is a way to delete a graph on yuml.me... you should ask them ^^ If there were one, I could document it...

**Comment by ireznik** [comment]
I wrote a dm to https://twitter.com/tobinharris who removed it afterwards.  I opened the issue much later but ran into the issue around dec 2018. Nevertheless thanks for the clarification.

**Comment by Nono1971** [comment]
you're welcome
