### ISSUE TITLE
Deprecations: DataCollectorInterface must implement reset() since symfony 3.4

### ISSUE THREAD

**Issue by MathieuThiry** [Nono1971/doctrine-yuml-bundle#2]
First of all, thanks for your bundle!

We could maybe add something like this to Onurb\Bundle\YumlBundle\DataCollector\DoctrineYumlDataCollector:

    public function reset()
    {
        $this->data = [];
    }

Thanks again!

**Comment by flaushi** [comment]
Yes, that would be great, I am also planning my upgrade to 4.0, and want to eliminate all deprecations beforehand.
Thanks in advance, great bundle!
