### ISSUE TITLE
Symfony4: The profiler template "OnurbYumlBundle:Toolbar:toolbar.html.twig" for data collector "doctrine_yuml" does not exist.

### ISSUE THREAD

**Issue by GerkinDev** [Nono1971/doctrine-yuml-bundle#4]
Hi!

I'm trying to run your bundle on my Symfony4 site, even if I know it is not really made for this version.

When loading a page, the web profiler toolbar displays:

> An error occurred while loading the web debug toolbar. 

Here is the error message:
```
Uncaught PHP Exception UnexpectedValueException: "The profiler template "OnurbYumlBundle:Toolbar:toolbar.html.twig" for data collector "doctrine_yuml" does not exist." at .../vendor/symfony/web-profiler-bundle/Profiler/TemplateManager.php line 90
```

So... Is there a way to get it working?

Thank you

**Comment by Nono1971** [comment]
Hi,
Didn't work on sf4 compatibility yet...

Almost the only part of symfony it uses is the profiler toolbar... the compatibility shouldn't be a major problem : all graph generation only uses Doctrine ;)

I should manage the migration ^-^ I let you know if I find a way to get it working meanwhile.

thank's for your issue report :)

**Comment by Nono1971** [comment]
Hi,

It's fixed !! I worked on SF4 compatibility, and I did it ! :)
To be complete, we have to wait the SF4 recipe to be merged in the recipes-contrib repo.

Meanwhile, you can make it work like this : 
update to 1.1
copy the template :
./vendor/onurb/doctrine-yuml-bundle/lib/Onurb/Bundle/YumlBundle/Ressources/views/Toolbar/toolbar.html.twig
in : ./templates/OnurbYumlBundle/Toolbar/toolbar.html.twig

then add the route config => create the file : config/routes/dev/yuml.yaml

    doctrine_yuml:
        resource: "@OnurbYumlBundle/Resources/config/routing.yml"

=> and everything should work great :)

**Comment by Nono1971** [comment]
I forgot... it still works for SF3 and SF2 of course :)

When the recipe will be OK (PR done), it will be installable with symfony flex in SF4 with the command line : 

    composer require onurb/doctrine-yuml-bundle

and the recipe will finalise the installation as I explained you how to do manually

**Comment by GerkinDev** [comment]
Really nice ! I'll check this out asap, but think like you have 1 more happy user :)

**Comment by flaushi** [comment]
I'm sorry, but for me (Symfony 3.4.4), the release of v1.1 broke the debug bar again. I am seeing the error message from above. After downgrading to 1.0.6, everything works again.

**Comment by Nono1971** [comment]
damn ! 
It's strange, I didn't change the location of the toolbar template... and all my tests still pass with sf3... I check this !! thank's for your report, I reopen the issue.

Infact, there's no new feature with 1.1, only sf4 compatibility... the most simple solution could be to use the version 1.0.x for sf3... and 1.1 for sf4... even if it would be better if the bundle where both compatible in 1.1... We'll find !!

**Comment by Nono1971** [comment]
Found !... it was so stupid ^^

    template: 'OnurbYumlBundle/Toolbar/toolbar.html.twig'

replaced by : 

    template: '@OnurbYuml/Toolbar/toolbar.html.twig'

you can test, everything should be OK now :)
