### ISSUE TITLE
Routes generated automatically

### ISSUE THREAD

**Issue by MathieuThiry** [Nono1971/doctrine-yuml-bundle#5]
It could be great if routes were generated automatically in 

    config/routes/dev/yuml.yaml

For new symfony projects, don't you think ?

**Comment by Nono1971** [comment]
The SF4 recipe automatically adds this file in the project, to link the the route defined in the bundle....

https://github.com/symfony/recipes-contrib/blob/master/onurb/doctrine-yuml-bundle/1.1/config/routes/dev/yuml.yaml

The routing is here => ./vendor/Onurb/Bundle/YumlBundle/Ressources/config/routing.yml

So, I don't see the point here ^^

Could you be more explicit about what you need ?

**Comment by MathieuThiry** [comment]
My bad, we can close this one. :)

Thanks !
