### ISSUE TITLE
Output extension

### ISSUE THREAD

**Issue by MathieuThiry** [Nono1971/doctrine-yuml-bundle#6]
It would be great to have a parameter that let us choose the output extension, like .svg, .png or .jpg.

Thanks again for your work !

**Comment by Nono1971** [comment]
YES, that's a good idea, I will do that :)

I think I will as well add the possibility to change the rendering => yuml.me offers 3 possibilities : 
plain (the one already use by the bundle), scruffy (uggly rendering), or boring (the same render plain does, except the color gradient).
=> it can be added also :)

Added in my todo list :)

**Comment by Nono1971** [comment]
Done ! 

I also added other customizations offered by yuml.me : 
the style as I told you yersterday, the direction (default is Top->Bottom, added left-Right, Right-left), and the scale (huge, big, normal, small, and tiny)... description added in README :)

Thanks for the idea :)

Bruno.

**Comment by MathieuThiry** [comment]
Great, I look forward to test it! :)

But can't you remove "symfony/symfony" from composer require ?

**Comment by Nono1971** [comment]
done !
