### ISSUE TITLE
idea: what about showing a page before starting rendering

### ISSUE THREAD

**Issue by SimonHeimberg** [Nono1971/doctrine-yuml-bundle#8]
The page shown when clicking on the debug icon shows some information and a link to render the graphic. Ideally, the parameters to render the graphic can be adapted in a form.

**Comment by Nono1971** [comment]
Hi !
First : Sorry for the delay not seeing your issue... some health troubles, and a strong medication... not following my emails for a while... but don't mind, thanks for your suggestion..  late answer is better than none, and I'm finally here  :)

All the configuration can already be set in the config/package/dev/yuml.yaml file... or with annotations...
For me, it's far enough, so when I decide parameters for rendering the graph in my project, I don't change it often... (in facts, never) ;) It would bother me to feed a form to get the render... I like the simplicity to just get it each time I need it in only one click.

But, so the only experience of my bundle is only my own one... it's not yet a NO, you still can try to convince me ! ;)

Let me know a little bit more about your idea... Which ones of the parameters would you want to change just before rendering the graph ?
Could you explain how it would be better for you to get this form to define rendering ?

**Comment by Nono1971** [comment]
Well, without answer, I close this issue so I am not convinced
 you'll reopen one if it is really important for you :)
