### ISSUE TITLE
Exception HTTP/2 stream 0 was not closed cleanly

### ISSUE THREAD

**Issue by Webonaute** [Nono1971/doctrine-yuml-bundle#9]
Got error like this when I try to run the command : 
bin/console --env=rc yuml:mappings -f test.svg
14:46:44 ERROR     [app] Exception HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) ["file" => "/Users/.../vendor/onurb/doctrine-yuml-bundle/lib/Onurb/Bundle/YumlBundle/Curl/Curl.php

**Comment by Nono1971** [comment]
Hi ! 
Sorry, on vacation, I didn't see your issue.
I made some tries by my side, and everything is working fine for me I don't manage to reproduce it...

But with some research, it seems that this error appears with curl 7.62.0 and higher, it seems there's a mess with protocols switching between http1.1 and http2... (you could check your version and tell me if it is your case).

Anyway, it seems that forcing the use of http1.1 should solve the problem...
I made a try forcing it on the Curl class __construct, it doesn't break it on my computer, but the wasn't reproduced, so I don't know if it will fix it... 

Could you test it for me ? and tell me if it fixes it ? (if it does I will push it :) )

in vendor/Onurb/doctrine-yuml-bundle/lib/Onurb/Bundle/YumlBundle/Curl/Curl.php 
 add this line at the end of the constructor (line 21) :

        curl_setopt($this->curl, CURL_HTTP_VERSION_1_1  , true);

**Comment by Nono1971** [comment]
Hi,

you never answered... maybe didn't you also reproduce this issue ??
I close...  Please reopen it if you still have the error. 
If it happens, pleeeaaase test the fix I proposed above, I won't push a patch if I'm not sure it really fixes the issue... and it is impossible to test for me, as I can't reproduce it on my system

Merci cousin du Quebec de ta compréhension ;) (Thanks, Quebec cousin for your comprehension)
